id: sample_step_one
hints: []
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
      - text: "Hello"
        delay: 2000
      - text: "Welcome to step 1 of the quest"
        delay: 1500
trigger:
  type: user_message_to_head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings: ["happy","glad"]:
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Great to hear you feel that way!
              delay: 1000
        - actionId: finish_step
			else:
				do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Please smile and try again!
              delay: 1000
